apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: simple-username-task
spec:
  params:
  - name: USERNAME
    type: string
    default: "john"
  steps:
  - name: script1
    image: registry.access.redhat.com/ubi9/ubi
    script: |
      #!/bin/bash
      echo "Hello $(params.USERNAME)"