apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: simple-username-pipeline
spec:
  params:
  - name: USERNAME
    type: string
  tasks:
  - name: simple-username-task
    taskRef:
      name: simple-username-task
    params:
    - name: USERNAME
      value: $(params.USERNAME)