---
# Source: lamp-app/charts/mariadb/templates/networkpolicy.yaml
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/instance: lamp-app
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/version: 12.2.2
  policyTypes:
    - Ingress
    - Egress
  egress:
    - {}
  ingress:
    - ports:
        - port: 3306
        - port: 3306
---
# Source: lamp-app/charts/mariadb/templates/primary/pdb.yaml
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/component: primary
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: lamp-app
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/component: primary
---
# Source: lamp-app/charts/mariadb/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
automountServiceAccountToken: false
---
# Source: lamp-app/charts/mariadb/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
type: Opaque
data:
  mariadb-root-password: "UGFzc3dvcmQxMjMh"
  mariadb-password: "bGFtcFBhc3N3b3Jk"
---
# Source: lamp-app/charts/mariadb/templates/primary/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/component: primary
data:
  my.cnf: |-
    [mysqld]
    skip-name-resolve
    explicit_defaults_for_timestamp
    basedir=/opt/bitnami/mariadb
    datadir=/bitnami/mariadb/data
    plugin_dir=/opt/bitnami/mariadb/plugin
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    tmpdir=/opt/bitnami/mariadb/tmp
    max_allowed_packet=16M
    bind-address=*
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    log-error=/opt/bitnami/mariadb/logs/mysqld.log
    character-set-server=UTF8
    collation-server=utf8_general_ci
    slow_query_log=0
    long_query_time=10.0
    binlog_expire_logs_seconds=2592000
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8
    plugin_dir=/opt/bitnami/mariadb/plugin
    
    [manager]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
---
# Source: lamp-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: lamp-app
data:
  index.php: |
    <?php
    $conn = new mysqli(
      getenv("DB_HOST"),
      getenv("DB_USER"),
      getenv("DB_PASSWORD"),
      getenv("DB_DATABASE")
    );

    if ($conn->connect_error) {
        die("Connection failed: " . $conn->connect_error);
    }

    echo "Connected successfully to MariaDB!";
    ?>
  apache.conf: |
    Listen 8080
    ServerName localhost

    <VirtualHost *:8080>
        DocumentRoot /var/www/html
    </VirtualHost>
---
# Source: lamp-app/charts/mariadb/templates/headless-svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: lamp-app-mariadb-headless
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  clusterIP: None
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/part-of: mariadb
---
# Source: lamp-app/charts/mariadb/templates/primary/svc.yaml
apiVersion: v1
kind: Service
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/component: primary
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/component: primary
---
# Source: lamp-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lamp-app
  labels:
    app: lamp-app
spec:
  type: ClusterIP
  selector:
    app: lamp-app
  ports:
    - port: 8080
      targetPort: 8080
---
# Source: lamp-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lamp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lamp-app
  template:
    metadata:
      labels:
        app: lamp-app
    spec:
      initContainers:
        - name: wait-for-db
          image: busybox
          command:
            - sh
            - -c
            - |
              until nc -z "lamp-app-mariadb" 3306; do
                echo "waiting for db..."
                sleep 2
              done
      containers:
        - name: apache-php
          image: "kosmolito/php82-nonroot:latest"
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: "lamp-app-mariadb"
            - name: DB_DATABASE
              value: lamp_db
            - name: DB_USER
              value: lamp_user
            - name: DB_PASSWORD
              value: lampPassword
          volumeMounts:
            - name: app-code
              mountPath: /var/www/html
            - name: app-code
              mountPath: /etc/apache2/ports.conf
              subPath: apache.conf
          resources: {}
      volumes:
        - name: app-code
          configMap:
            name: lamp-app
---
# Source: lamp-app/charts/mariadb/templates/primary/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lamp-app-mariadb
  namespace: "default"
  labels:
    app.kubernetes.io/instance: lamp-app
    app.kubernetes.io/name: mariadb
    app.kubernetes.io/version: 12.2.2
    app.kubernetes.io/part-of: mariadb
    app.kubernetes.io/component: primary
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/instance: lamp-app
      app.kubernetes.io/name: mariadb
      app.kubernetes.io/part-of: mariadb
      app.kubernetes.io/component: primary
  serviceName: lamp-app-mariadb-headless
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      annotations:
        checksum/configuration: 1c1f39b0b7702584d13dd2f7b14824386e63b52fb555759eb7c073d55a7e5610
      labels:
        app.kubernetes.io/instance: lamp-app
        app.kubernetes.io/name: mariadb
        app.kubernetes.io/version: 12.2.2
        app.kubernetes.io/part-of: mariadb
        app.kubernetes.io/component: primary
    spec:
      
      automountServiceAccountToken: false
      serviceAccountName: lamp-app-mariadb
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app.kubernetes.io/instance: lamp-app
                    app.kubernetes.io/name: mariadb
                    app.kubernetes.io/component: primary
                topologyKey: kubernetes.io/hostname
              weight: 1
      securityContext:
        fsGroup: 1001
        fsGroupChangePolicy: Always
        supplementalGroups: []
        sysctls: []
      initContainers:
        - name: preserve-logs-symlinks
          image: registry-1.docker.io/bitnami/mariadb:latest
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          resources:
            limits:
              cpu: 750m
              ephemeral-storage: 2Gi
              memory: 768Mi
            requests:
              cpu: 500m
              ephemeral-storage: 50Mi
              memory: 512Mi
          command:
            - /bin/bash
          args:
            - -ec
            - |
              #!/bin/bash

              . /opt/bitnami/scripts/libfs.sh
              # We copy the logs folder because it has symlinks to stdout and stderr
              if ! is_dir_empty /opt/bitnami/mariadb/logs; then
                cp -r /opt/bitnami/mariadb/logs /emptydir/app-logs-dir
              fi
          env:
            - name: OPENSSL_FIPS
              value: "yes"
          volumeMounts:
           - name: empty-dir
             mountPath: /emptydir
      containers:
        - name: mariadb
          image: registry-1.docker.io/bitnami/mariadb:latest
          imagePullPolicy: "IfNotPresent"
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
              - ALL
            privileged: false
            readOnlyRootFilesystem: true
            runAsGroup: 1001
            runAsNonRoot: true
            runAsUser: 1001
            seLinuxOptions: {}
            seccompProfile:
              type: RuntimeDefault
          env:
            - name: BITNAMI_DEBUG
              value: "false"
            - name: MARIADB_ROOT_PASSWORD_FILE
              value: /opt/bitnami/mariadb/secrets/mariadb-root-password
            - name: MARIADB_USER
              value: "lamp_user"
            - name: MARIADB_PASSWORD_FILE
              value: /opt/bitnami/mariadb/secrets/mariadb-password
            - name: MARIADB_DATABASE
              value: "lamp_db"
            - name: MARIADB_ENABLE_SSL
              value: "no"
            - name: OPENSSL_FIPS
              value: "yes"
          ports:
            - name: mysql
              containerPort: 3306
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 120
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mariadb-admin status -uroot -p"${password_aux}"
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            exec:
              command:
                - /bin/bash
                - -ec
                - |
                  password_aux="${MARIADB_ROOT_PASSWORD:-}"
                  if [[ -f "${MARIADB_ROOT_PASSWORD_FILE:-}" ]]; then
                      password_aux=$(cat "$MARIADB_ROOT_PASSWORD_FILE")
                  fi
                  mariadb-admin ping -uroot -p"${password_aux}"
          resources:
            limits:
              cpu: 750m
              ephemeral-storage: 2Gi
              memory: 768Mi
            requests:
              cpu: 500m
              ephemeral-storage: 50Mi
              memory: 512Mi
          volumeMounts:
            - name: data
              mountPath: /bitnami/mariadb
            - name: config
              mountPath: /opt/bitnami/mariadb/conf/my.cnf
              subPath: my.cnf
            - name: mariadb-credentials
              mountPath: /opt/bitnami/mariadb/secrets/
            - name: empty-dir
              mountPath: /tmp
              subPath: tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mariadb/conf
              subPath: app-conf-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mariadb/tmp
              subPath: app-tmp-dir
            - name: empty-dir
              mountPath: /opt/bitnami/mariadb/logs
              subPath: app-logs-dir
      volumes:
        - name: empty-dir
          emptyDir: {}
        - name: config
          configMap:
            name: lamp-app-mariadb
        - name: mariadb-credentials
          secret:
            secretName: lamp-app-mariadb
            items:
              - key: mariadb-root-password
                path: mariadb-root-password
              - key: mariadb-password
                path: mariadb-password
        - name: data
          emptyDir: {}
---
# Source: lamp-app/templates/route.yaml
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: lamp-app
  labels:
    app: lamp-app
spec:
  port:
    targetPort: 8080
  to:
    kind: ""
    name: lamp-app
