apiVersion: v1
kind: Secret
# This secret is used to authenticate with the Git repository when Tekton clones the repository during the pipeline execution.
metadata:
  name: ex288-study-git-secret
  annotations:
    # This annotation is required for Tekton to use this secret when cloning git repositories.
    tekton.dev/git-0: "https://github.com/kosmolito/ex288-study"
type: kubernetes.io/basic-auth
stringData:
  username: kosmolito
  password: Password123